import { IImageData, IMembers, INav, ICaritasHistory } from "./types";
import JosephEtukImg from "@/assets/images/members/joseph_etuk.png";
import FelicitaImg from "@/assets/images/members/MaFelicita.png";
import GerardInohIimg from "@/assets/images/members/gerard_inoh.png";
import EkobokeImg from "@/assets/images/members/Mr._Ekeboke_Francis.png";
import UdoetteImg from "@/assets/images/members/udoette.jpg";
import ObongJosephImg from "@/assets/images/members/obong_joseph.jpg";
import LinusNkanImg from "@/assets/images/members/HC-Linus-Nkan.jpg";
import EphraimNkangaImg from "@/assets/images/members/ephraim_nkanga.jpeg";
import PatrickUsangeImg from "@/assets/images/members/patrick_usanga.jpeg";
import AnthonyOffiongImg from "@/assets/images/members/anthony_offiong.jpeg";

export const ImageDataList: Array<IImageData> = [
  {
    id: 1,
    imageLink:
      "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2073&q=80",
    description: "Books on a table",
  },
  {
    id: 2,
    imageLink:
      "https://images.unsplash.com/photo-1491841550275-ad7854e35ca6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1974&q=80",
    description: "Kid reading",
  },
  {
    id: 3,
    imageLink:
      "https://images.unsplash.com/photo-1591253363983-41adcdba3ed6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjN8fG5vbiUyMHByb2ZpdHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=600&q=60",
    description: "protesting for a better cause",
  },
  {
    id: 4,
    imageLink:
      "https://images.unsplash.com/photo-1608686207856-001b95cf60ca?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1854&q=80",
    description: "Humanitarian aid",
  },
  {
    id: 5,
    imageLink:
      "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2073&q=80",
    description: "Food packages",
  },
  {
    id: 6,
    imageLink:
      "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fGNodXJjaCUyMGNoYXJpdHl8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=600&q=60",
    description: "Smiling children",
  },
  {
    id: 7,
    imageLink:
      "https://images.unsplash.com/photo-1622037022630-9fd9c076e565?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8dG9nZXRoZXJuZXNzfGVufDB8fDB8fHww&auto=format&fit=crop&w=600&q=60",
    description: "togetherness",
  },
  {
    id: 8,
    imageLink:
      "https://plus.unsplash.com/premium_photo-1661602481757-f9e91fb2d3d5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTN8fHRvZ2V0aGVybmVzc3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=600&q=60",
    description: "people together",
  },
  {
    id: 9,
    imageLink:
      "https://images.unsplash.com/photo-1544390409-8b6412683bc9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fGdpdmluZ3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=600&q=60",
    description: "out in the beach",
  },
];

export const membersDataList: Array<IMembers> = [
  {
    id: 1,
    img: null,
    name: "Dr. Emmanuel Philip Effiong",
    alias: "Emmanuel Effiong",
    imgDescription: "Dr. Emmanuel Philip Effiong",
    phoneNumber: "",
    position: "Eldest/ Founding Member",
    profession: "Doctor",
    email: "",
    homeParish: "",
    domParish: "",
    Address: "",
    yearJoined: "",
  },
  {
    id: 2,
    img: JosephEtukImg,
    name: "Sir. Joseph Michael Etuk (KSJI)",
    alias: "Joseph Etuk",
    imgDescription: "Image of Joseph Michael Etuk",
    position: "Assistant Eldest/ Founding Member",
    profession: "Town Planner",
    phoneNumber: "08023229907",
    email: "Jmet_al@yahoo.com",
    homeParish: "St James Parish, Ibam Edet, Akwa Ibom State, Nigeria",
    domParish: "St John, 72 Abak Road, Uyo,  Akwa Ibom State,  Nigeria",
    Address:
      "No 1 Bishop Moynagh Pastoral Centre Lane,Uyo Akwa Ibom State, Nigeria",
    yearJoined: "September, 1998",
  },
  {
    id: 3,
    img: null,
    name: "Hon. (Obong) Anthony Effiong Okpon",
    alias: "Anthony Okpon",
    imgDescription: "Image of Obong Anthony Okpo",
    position: "member",
    profession: "",
    phoneNumber: "",
    email: "",
    homeParish: "",
    domParish: "",
    Address: "",
    yearJoined: "",
  },
  {
    id: 4,
    img: null,
    name: "Prof. Emmanuel Peter Udofia",
    alias: "Emmanuel Udofia",
    imgDescription: "Image of Prof. Emmanuel Udofia",
    position: "Founding Member",
    profession: "Lecturer",
    phoneNumber: "08026692702",
    email: "udofiaemmanuel085@gmail.com",
    homeParish: "St Paul Minya",
    domParish: "St John's Parish Abak Road Uyo",
    Address: "64 Idoro Road by basse Engineering Uyo",
    yearJoined: "2003",
  },
  {
    id: 5,
    img: null,
    name: "Mr. Sylvester Okon Akpan",
    alias: "Sylvester Akpan",
    imgDescription: "Image of Mr. Sylvester Akpan",
    position: "Treasurer/ Founding Member",
    profession: "",
    phoneNumber: "",
    email: "",
    homeParish: "",
    domParish: "",
    Address: "",
    yearJoined: "",
  },
  {
    id: 6,
    img: LinusNkanImg,
    name: "Dr. Nsikan Linus Nkan",
    alias: "Nsikan Nkan",
    imgDescription: "Image of Dr. Nsikan Linus Nkan",
    position: "Founding Member",
    profession: "Commissioner",
    phoneNumber: "",
    email: "",
    homeParish: "",
    domParish: "",
    Address: "",
    yearJoined: "",
  },
  {
    id: 7,
    img: null,
    name: "Mr. Oliver Otu Udoukpo",
    alias: "Oliver Udoukpo",
    imgDescription: "Image of Mr. Oliver Udoukpo",
    position: "Founding Member",
    profession: "",
    phoneNumber: "",
    email: "",
    homeParish: "",
    domParish: "",
    Address: "",
    yearJoined: "",
  },
  {
    id: 8,
    img: PatrickUsangeImg,
    name: "Mr. Patrick Dominic Usanga (KSM)",
    alias: "Patrick Usanga",
    imgDescription: "Image of Mr. Patrick Usanga",
    position: "Founding Member",
    profession: "",
    phoneNumber: "",
    email: "",
    homeParish: "",
    domParish: "",
    Address: "",
    yearJoined: "",
  },
  {
    id: 9,
    img: EphraimNkangaImg,
    name: "Eng. Ephraim Anthony Nkanga",
    alias: "Ephraim Nkanga",
    imgDescription: "Image of Mr. Ephraim Nkanga",
    position: "Founding Member",
    profession: "Engineering",
    phoneNumber: "08029435848",
    email: "eankanga@gmail.com",
    homeParish: "St Paul's, Ikot Ofon Ikono",
    domParish: "St. John's,  72 Abak Road, Uyo.",
    Address: "40 House of Assembly Road, Uyo",
    yearJoined: "April, 2003",
  },
  {
    id: 10,
    img: null,
    name: "Barr. Godwin Gabriel Umoh",
    alias: "Godwin Umoh",
    imgDescription: "Image of Barr. Godwin Gabriel Umoh",
    position: "Founding Member",
    profession: "",
    phoneNumber: "",
    email: "",
    homeParish: "",
    domParish: "",
    Address: "",
    yearJoined: "",
  },
  {
    id: 11,
    img: EkobokeImg,
    name: "Mr. Ekoboke Luke Joseph (KSM)",
    alias: "Ekoboke Joseph",
    imgDescription: "Image of Ekoboke Joseph",
    position: "Member",
    profession: "",
    phoneNumber: "",
    email: "",
    homeParish: "",
    domParish: "",
    Address: "",
    yearJoined: "",
  },
  {
    id: 12,
    img: GerardInohIimg,
    name: "Mr. Gerald Gordian Inoh",
    alias: "Gerald Inoh",
    imgDescription: "Image of Gerald Gordian Inoh",
    phoneNumber: "08023352977",
    position: "Financial Secretary/ Public Relations Officer",
    profession: "Scientist",
    email: "",
    homeParish: "St. Theresa Parish, Ikot Edibon, Nsit Uboum",
    domParish: "St John, 72 Abak Road, Uyo,  Akwa Ibom State,  Nigeria",
    Address: "Cardinal Ekanem Road, Ik. Adaidem, Ibiono",
    yearJoined: "May, 2013",
  },
  {
    id: 13,
    img: UdoetteImg,
    name: "Mr. Dominic Asuquo Udoette",
    alias: "Dominic Udoette",
    imgDescription: "Image of Dominic Asuquo Udoette",
    position: "provost",
    profession: "Entrepreneur",
    phoneNumber: "08037703142",
    email: "ekayudoette@gmail.com",
    homeParish: "St Peter's parish, ibiono ibom",
    domParish: "St John's parish 72 abak road uyo",
    Address: "14 itam park road",
    yearJoined: "April, 2012",
  },
  {
    id: 14,
    img: AnthonyOffiongImg,
    name: "Mr. Anthony Uko Offiong",
    alias: "Anthony Offiong",
    imgDescription: "Image of Mr. Anthony Offiong",
    position: "Wellface Officer",
    profession: "Treasurer",
    phoneNumber: "",
    email: "",
    homeParish: "",
    domParish: "",
    Address: "",
    yearJoined: "",
  },
  {
    id: 15,
    img: ObongJosephImg,
    name: "Obong Joseph Etim Ibok",
    alias: "Joseph Ibok",
    imgDescription: "Image of Obong Joseph Etim Ibok",
    phoneNumber: "08028860996",
    position: "Secretary",
    profession: "Chartered Manager",
    email: "awakgerald@gmail.com",
    homeParish: "St. Lawrence, Eman Uruan",
    domParish: "Sacred Heart, Aka, Uyo",
    Address: "11 Etim Udosen Close, Atan Offot, Uyo",
    yearJoined: "May, 2015",
  },
  {
    id: 16,
    img: null,
    name: "Dr. Alfred Udo Udoh",
    alias: "Alfred Udoh",
    imgDescription: "Image of Alfred Udoh",
    position: "Assitant Secretary",
    profession: "Agriculturist",
    phoneNumber: "0803 389 2976",
    email: "Udohfred7@gmail.com",
    homeParish: "St Anthony's, Mbiabong Ikot Udofia",
    domParish: "Sacred Heart Parish, Aka Offot Uyo",
    Address: "Ikot Akpan Abia, Ibesikpo Asutan",
    yearJoined: "March, 2015",
  },
  {
    id: 17,
    img: null,
    name: "Sir. James Etim Ukpong (KSJI)",
    alias: "James Ukpong",
    imgDescription: "Image of Mr. James Ukpong",
    position: "Member",
    profession: "",
    phoneNumber: "",
    email: "",
    homeParish: "",
    domParish: "",
    Address: "",
    yearJoined: "",
  },
  {
    id: 18,
    img: FelicitaImg,
    name: "Prof. (Mrs.) Felicia Saturday Ekpu",
    alias: "Felicia Ekpu",
    imgDescription: "Image of Felicia Saturday Ekpu",
    position: "Member",
    profession: "Professor",
    phoneNumber: "08033283612",
    email: "effsatt@gmail.com",
    homeParish: "St. Peter Parish, Adiasim, Essien Udim LGA",
    domParish: "St John, 72 Abak Road, Uyo,  Akwa Ibom State,  Nigeria",
    Address: "Department of Human Kinetics, University of Uyo, Nigeria",
    yearJoined: "December, 2022",
  },
];

export const TrusteesTeam: Array<IMembers> = [
  {
    id: 1,
    img: null,
    name: "Dr. Emmanuel Philip Effiong",
    alias: "Emmanuel Effiong",
    imgDescription: "Dr. Emmanuel Philip Effiong",
    phoneNumber: "",
    position: "Eldest",
    profession: "Doctor",
    email: "",
    homeParish: "",
    domParish: "",
    Address: "",
    yearJoined: "",
  },
  {
    id: 2,
    img: JosephEtukImg,
    name: "Sir. Joseph Michael Etuk",
    alias: "Joseph Etuk",
    imgDescription: "Image of Joseph Michael Etuk",
    position: "Assistant Eldest",
    profession: "Town Planner",
    phoneNumber: "08023229907",
    email: "Jmet_al@yahoo.com",
    homeParish: "St James Parish, Ibam Edet, Akwa Ibom State, Nigeria",
    domParish: "St John, 72 Abak Road, Uyo,  Akwa Ibom State,  Nigeria",
    Address:
      "No 1 Bishop Moynagh Pastoral Centre Lane,Uyo Akwa Ibom State, Nigeria",
    yearJoined: "September, 1998",
  },
  {
    id: 3,
    img: null,
    name: "Mr. Obong Anthony Okpon",
    alias: "Anthony Okpon",
    imgDescription: "Image of Obong Anthony Okpo",
    position: "member",
    profession: "",
    phoneNumber: "",
    email: "",
    homeParish: "",
    domParish: "",
    Address: "",
    yearJoined: "",
  },
  {
    id: 4,
    img: null,
    name: "Mr. Sylvester Okon Akpan",
    alias: "Sylvester Akpan",
    imgDescription: "Image of Mr. Sylvester Akpan",
    position: "Treasurer/ Founding Member",
    profession: "",
    phoneNumber: "",
    email: "",
    homeParish: "",
    domParish: "",
    Address: "",
    yearJoined: "",
  },
  {
    id: 5,
    img: GerardInohIimg,
    name: "Mr. Gerald Gordian Inoh",
    alias: "Gerald Inoh",
    imgDescription: "Image of Gerald Gordian Inoh",
    phoneNumber: "08023352977",
    position: "Financial Secretary/ Public Relations Officer",
    profession: "Scientist",
    email: "",
    homeParish: "St. Theresa Parish, Ikot Edibon, Nsit Uboum",
    domParish: "St John, 72 Abak Road, Uyo,  Akwa Ibom State,  Nigeria",
    Address: "Cardinal Ekanem Road, Ik. Adaidem, Ibiono",
    yearJoined: "May, 2013",
  },
];

export const managementTeam: Array<IMembers> = [
  {
    id: 1,
    img: null,
    name: "Dr. Emmanuel Philip Effiong",
    alias: "Emmanuel Effiong",
    imgDescription: "Dr. Emmanuel Philip Effiong",
    phoneNumber: "",
    position: "Eldest",
    profession: "Doctor",
    email: "",
    homeParish: "",
    domParish: "",
    Address: "",
    yearJoined: "",
  },
  {
    id: 2,
    img: JosephEtukImg,
    name: "Sir. Joseph Michael Etuk",
    alias: "Joseph Etuk",
    imgDescription: "Image of Joseph Michael Etuk",
    position: "Assistant Eldest",
    profession: "Town Planner",
    phoneNumber: "08023229907",
    email: "Jmet_al@yahoo.com",
    homeParish: "St James Parish, Ibam Edet, Akwa Ibom State, Nigeria",
    domParish: "St John, 72 Abak Road, Uyo,  Akwa Ibom State,  Nigeria",
    Address:
      "No 1 Bishop Moynagh Pastoral Centre Lane,Uyo Akwa Ibom State, Nigeria",
    yearJoined: "September, 1998",
  },
  {
    id: 3,
    img: ObongJosephImg,
    name: "Obong Joseph Etim Ibok",
    alias: "Joseph Ibok",
    imgDescription: "Image of Obong Joseph Etim Ibok",
    phoneNumber: "08028860996",
    position: "Secretary",
    profession: "Chartered Manager",
    email: "awakgerald@gmail.com",
    homeParish: "St. Lawrence, Eman Uruan",
    domParish: "Sacred Heart, Aka, Uyo",
    Address: "11 Etim Udosen Close, Atan Offot, Uyo",
    yearJoined: "May, 2015",
  },
  {
    id: 4,
    img: null,
    name: "Dr. Alfred Udo Udoh",
    alias: "Alfred Udoh",
    imgDescription: "Image of Alfred Udoh",
    position: "Assitant Secretary",
    profession: "Agriculturist",
    phoneNumber: "0803 389 2976",
    email: "Udohfred7@gmail.com",
    homeParish: "St Anthony's, Mbiabong Ikot Udofia",
    domParish: "Sacred Heart Parish, Aka Offot Uyo",
    Address: "Ikot Akpan Abia, Ibesikpo Asutan",
    yearJoined: "March, 2015",
  },
  {
    id: 5,
    img: null,
    name: "Mr. Sylvester Okon Akpan",
    alias: "Sylvester Akpan",
    imgDescription: "Image of Mr. Sylvester Akpan",
    position: "Treasurer/ Founding Member",
    profession: "",
    phoneNumber: "",
    email: "",
    homeParish: "",
    domParish: "",
    Address: "",
    yearJoined: "",
  },
  {
    id: 6,
    img: GerardInohIimg,
    name: "Mr. Gerald Gordian Inoh",
    alias: "Gerald Inoh",
    imgDescription: "Image of Gerald Gordian Inoh",
    phoneNumber: "08023352977",
    position: "Financial Secretary/ Public Relations Officer",
    profession: "Scientist",
    email: "",
    homeParish: "St. Theresa Parish, Ikot Edibon, Nsit Uboum",
    domParish: "St John, 72 Abak Road, Uyo,  Akwa Ibom State,  Nigeria",
    Address: "Cardinal Ekanem Road, Ik. Adaidem, Ibiono",
    yearJoined: "May, 2013",
  },
  {
    id: 7,
    img: UdoetteImg,
    name: "Mr. Dominic Asuquo Udoette",
    alias: "Dominic Udoette",
    imgDescription: "Image of Dominic Asuquo Udoette",
    position: "provost",
    profession: "Entrepreneur",
    phoneNumber: "08037703142",
    email: "ekayudoette@gmail.com",
    homeParish: "St Peter's parish, ibiono ibom",
    domParish: "St John's parish 72 abak road uyo",
    Address: "14 itam park road",
    yearJoined: "April, 2012",
  },
  {
    id: 8,
    img: AnthonyOffiongImg,
    name: "Mr. Anthony Uko Offiong",
    alias: "Anthony Offiong",
    imgDescription: "Image of Mr. Anthony Offiong",
    position: "Wellface Officer",
    profession: "Treasurer",
    phoneNumber: "",
    email: "",
    homeParish: "",
    domParish: "",
    Address: "",
    yearJoined: "",
  },
];

export const projectCommittee: Array<IMembers> = [
  {
    id: 1,
    img: null,
    name: "Mr. Sylvester Okon Akpan",
    alias: "Sylvester Akpan",
    imgDescription: "Image of Mr. Sylvester Akpan",
    position: "Chairman/ Founding Member",
    profession: "",
    phoneNumber: "",
    email: "",
    homeParish: "",
    domParish: "",
    Address: "",
    yearJoined: "",
  },
  {
    id: 2,
    img: JosephEtukImg,
    name: "Sir. Joseph Michael Etuk",
    alias: "Joseph Etuk",
    imgDescription: "Image of Joseph Michael Etuk",
    position: "Member",
    profession: "Town Planner",
    phoneNumber: "08023229907",
    email: "Jmet_al@yahoo.com",
    homeParish: "St James Parish, Ibam Edet, Akwa Ibom State, Nigeria",
    domParish: "St John, 72 Abak Road, Uyo,  Akwa Ibom State,  Nigeria",
    Address:
      "No 1 Bishop Moynagh Pastoral Centre Lane,Uyo Akwa Ibom State, Nigeria",
    yearJoined: "September, 1998",
  },
  {
    id: 3,
    img: null,
    name: "Prof. Emmanuel Peter Udofia",
    alias: "Emmanuel Udofia",
    imgDescription: "Image of Prof. Emmanuel Udofia",
    position: "Founding Member",
    profession: "Lecturer",
    phoneNumber: "08026692702",
    email: "udofiaemmanuel085@gmail.com",
    homeParish: "St Paul Minya",
    domParish: "St John's Parish Abak Road Uyo",
    Address: "64 Idoro Road by basse Engineering Uyo",
    yearJoined: "2003",
  },
];

export const financeCommittee: Array<IMembers> = [
  {
    id: 1,
    img: null,
    name: "Mr. Sylvester Okon Akpan",
    alias: "Sylvester Akpan",
    imgDescription: "Image of Mr. Sylvester Akpan",
    position: "Chairman/ Founding Member",
    profession: "",
    phoneNumber: "",
    email: "",
    homeParish: "",
    domParish: "",
    Address: "",
    yearJoined: "",
  },
  {
    id: 2,
    img: GerardInohIimg,
    name: "Mr. Gerald Gordian Inoh",
    alias: "Gerald Inoh",
    imgDescription: "Image of Gerald Gordian Inoh",
    phoneNumber: "08023352977",
    position: "Member",
    profession: "Scientist",
    email: "",
    homeParish: "St. Theresa Parish, Ikot Edibon, Nsit Uboum",
    domParish: "St John, 72 Abak Road, Uyo,  Akwa Ibom State,  Nigeria",
    Address: "Cardinal Ekanem Road, Ik. Adaidem, Ibiono",
    yearJoined: "May, 2013",
  },
];

export const welfareCommittee: Array<IMembers> = [
  {
    id: 1,
    img: AnthonyOffiongImg,
    name: "Mr. Anthony Uko Offiong",
    alias: "Anthony Offiong",
    imgDescription: "Image of Mr. Anthony Offiong",
    position: "Head",
    profession: "Treasurer",
    phoneNumber: "",
    email: "",
    homeParish: "",
    domParish: "",
    Address: "",
    yearJoined: "",
  },
  {
    id: 2,
    img: UdoetteImg,
    name: "Mr. Dominic Asuquo Udoette",
    alias: "Dominic Udoette",
    imgDescription: "Image of Dominic Asuquo Udoette",
    position: "Member",
    profession: "Entrepreneur",
    phoneNumber: "08037703142",
    email: "ekayudoette@gmail.com",
    homeParish: "St Peter's parish, ibiono ibom",
    domParish: "St John's parish 72 abak road uyo",
    Address: "14 itam park road",
    yearJoined: "April, 2012",
  },
];

export const navItems: Array<INav> = [
  {
    id: 1,
    label: "Home",
    link: "/",
  },
  {
    id: 2,
    label: "About Us",
    link: "/aboutus",
  },
  {
    id: 3,
    label: "Projects",
    link: "/projects",
  },
  {
    id: 4,
    label: "Members",
    link: "/members",
  },
  // {
  //   id: 5,
  //   label: "Gallery",
  //   link: "/gallery",
  // },
  {
    id: 7,
    label: "Donate",
    link: "/donate",
  },
  {
    id: 6,
    label: "Contact Us",
    link: "/contactus",
  },
  // {
  //   id: 7,
  //   label: "Admin",
  //   link: "/admin",
  // },
];

export const caritasHistory: Array<ICaritasHistory> = [
  {
    id: 1,
    title: "Birth of the Foundation at St. John Parish, Uyo",
    paragraph:
      "What is known today as \"CARITAS CHRISTIAN ELDERS FOUNDATION\" began at St. John Parish Abak Road, Uyo Diocese, Nigeria, in 2006. Mr. Ephraim Anthony Nkanga started hosting his Catholic friends from the parish, including priests at his residence at Akwa Ibom State House of Assembly Road, Uyo to ease the boredom usually associated with Easter Monday holidays. The original group included Dr. Emmanuel Philip Effiong, Mr. Joseph Etuk, Mr. Boniface Udo Udo (Late), Mr. Nsikan Linus Nkan, Dr. Emmanuel Peter Udofia, Barrister Godwin Gabriel Umoh, Mr. Patrick Dominic Usanga, Mr. Oliver Otu Udoukpo, Mr. Sylvester Okon Akpan, Barrister Christopher Michael Inwang, Mr. Iniobong Michael Eka, Mr. Patrick Archibong Udoh (Late), Mr. Michael Effiong Inyang, and Mr. Anthony Athanasius Akpanobong (Late). The last five foundation members dropped out of the group shortly afterwards.",
    timeline: "2006",
    display: true,
  },
  {
    id: 2,
    title: "Formation of St. John Mass Centre",
    paragraph:
      "Shortly after the creation of St. John Mass Center in 1996, a group made up of senior members of the Youth Mass Center were selected to serve in the church pastoral council. When the Mass Center was elevated to a Quasi-Parish, the same members retained their offices in the pastoral council.",
    timeline: "1996",
    display: true,
  },
  {
    id: 3,
    title: "Expansion Beyond St. John Parish",
    paragraph:
      "Following the evangelization efforts by the foundation, members from the other parishes within the Diocese of Uyo have come to join the pioneer members at St. John parish.",
    timeline: "Early 2000s",
    display: true,
  },
  {
    id: 4,
    title: "The Name 'Elders Forum' is Born",
    paragraph:
      "The name \"Elders Forum\" originated from Mr. Ephraim Anthony Nkanga and Mr. Patrick Dominic Usanga, who were affectionately called \"Elders\" by the parishioners due to their active roles in the parish. In the early days, Dr. Emmanuel Philip Effiong led the group, serving not only as parish council chairman but also as a medical practitioner, which made it difficult for him to function as a leader of the group. The group then unanimously chose Mr. Boniface Udo Udo, known for his human management expertise, to provide the needed leadership. He therefore became the first to adopt the title \"The Eldest\", meaning the Eldest of all the Elders, while Dr. Emmanuel Philip Effiong became the Assistant Eldest.",
    timeline: "Early 2000s",
    display: true,
  },
  {
    id: 5,
    title:
      "Registration with CAC — Caritas Christian Elders Foundation",
    paragraph:
      "For the group to operate as a legal entity, it sought for registration with Nigeria's Corporate Affairs Commission (CAC), and was duly registered as \"CARITAS CHRISTIAN ELDERS FOUNDATION\" with their incorporated trustees on June 17, 2014, for the Companies and Allied Matters Act No. 1 of 1990.",
    timeline: "June 17, 2014",
    display: true,
  },
  {
    id: 6,
    title: "Leadership Milestones",
    paragraph:
      "In the early days, Dr. Emmanuel Philip Effiong led the Foundation while serving as Parish Council Chairman, but his demanding medical practice made it difficult to continue. The group then unanimously chose Mr. Boniface Udo Udo, known for his management expertise, to lead. He became the first to hold the title of \"The Eldest of the Elders\", while Dr. Effiong stepped into the role of Assistant Eldest.",
    timeline: "Timeless",
    display: false,
  },
  {
    id: 7,
    title: "Meeting Locations",
    paragraph:
      "Initially, the Foundation held its meetings at Ephraim Anthony Nkanga’s residence on House of Assembly Road, Uyo. However, as membership grew, meetings were moved to Number 14, Akpan Etuk Street, where Elder Anthony Effiong Okpon prepared a dedicated meeting hall for the group.",
    timeline: "Mid 2000s",
    display: false,
  },
];
